### ISSUE TITLE
Doesn't compile on rustc 1.59.0-nightly

### ISSUE THREAD

**Issue by Aivean** [RSSchermer/web_glitz.rs#2]
```bash
rustc --version
rustc 1.59.0-nightly (efec54529 2021-12-04)
npm --version
7.15.1
node --version
v15.14.0
```

Rust compilation fails during `npm run serve`:

```bash
npm run serve

> serve
> webpack-dev-server

🧐  Checking for wasm-pack...

✅  wasm-pack is installed.

ℹ️  Compiling your crate...

ℹ ｢wds｣: Project is running at http://localhost:8080/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /.../web_glitz.rs/examples/4_blit
wasm-pack error: [INFO]: Checking for the Wasm target...
[INFO]: Compiling to Wasm...
   Compiling proc-macro2 v1.0.32


error[E0557]: feature has been removed
  --> /Users/Aivean/.cargo/registry/src/github.com-1ecc6299db9ec823/staticvec-0.10.8/src/lib.rs:33:3
   |
33 |   const_evaluatable_checked,
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^ feature has been removed
   |
   = note: renamed to `generic_const_exprs`

error[E0557]: feature has been removed
  --> /Users/Aivean/.cargo/registry/src/github.com-1ecc6299db9ec823/staticvec-0.10.8/src/lib.rs:38:3
   |
38 |   const_generics,
   |   ^^^^^^^^^^^^^^ feature has been removed
   |
   = note: removed in favor of `#![feature(adt_const_params)]` and `#![feature(generic_const_exprs)]`
```

Is support for stable rust planned, or should I downgrade my `rustc` to try out this project?  Thank you.

**Comment by RSSchermer** [comment]
Apologies for the delay, this was blocked waiting on a new release for `staticvec`. I've just published web-glitz `0.3.0`, which should compile correctly on current nightly.

> Is support for stable rust planned, or should I downgrade my rustc to try out this project? Thank you.

This crate relies on compile-time `const` evaluation to statically describe pipeline interfaces. This is rather core to the API and allows for an essentially checkless render-loop. The required `const` evaluation is currently still partially feature-gated however. 

Support for stable Rust is planned, insofar that all essential feature dependencies are expected to eventually make it into stable Rust. How long that will take however, I'm note sure of. There's been quite a bit of movement on `const` evaluation features this year, so hopefully this won't be too long, but I'd still expect it to be on the order of ~1 year.
